version: 2.0
jobs:

  test:
    docker:
      - image: lathonez/node-selenium

    working_directory: /notely

    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}

      - run: npm i

      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: lint
          command: npm run lint

      - run:
          name: setup test reports folder
          command: mkdir -p /tmp/junit/

      - run:
          name: unit test
          command: xvfb-run npm run test-ci

      - store_test_results:
          path: /tmp/junit/

workflows:
  version: 2
  main:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
               - master