version: 2.0
jobs:

  build:
    docker:
      - image: lathonez/node-selenium

    working_directory: /notely

    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}

      - run: npm i

      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: lint
          command: npm run lint

      - run:
          name: setup test reports folder
          command: mkdir -p /tmp/junit/

      - run:
          name: unit test
          command: xvfb-run npm test

      - store_test_results:
          path: /tmp/junit/

      - run:
          name: Deploy
          # only deploy on master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config --global user.email "shazleto@gmail.com"
              git config --global user.name "Circle CI Builder"
              npm run release
            fi
